openapi: 3.0.0
info:
  title: todoList
  description: todoList app API
  version: 0.1.9

servers:
  - url: https://todo-backend-app.up.railway.app/api
    description: production server
  - url: http://localhost:3000/api
    description: local server

paths:
  /todoList:
    get:
      tags:
        - todoList
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /send:
    post:
      tags:
        - Todo
      requestBody:
        description: add todo
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                todo:
                  type: string
                status:
                  type: boolean
      responses:
        "200":
          description: ToDo add
