openapi: 3.0.0
info:
  title: todoList
  description: todoList app API
  version: 0.1.9

servers:
  - url: http://api.example.com/api
    description: production server
  - url: http://localhost:3000/api
    description: local server

paths:
  /todoList:
    get:
      tags:
        - todoList
      responses:
        '200':
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

